export const OnlyOneRestaurantInJapan = [
  { id: 1, name: "山才", gmap: "https://maps.app.goo.gl/M5iy2GLEukxDBPR96"},
  { id: 2, name: "うなぎ魚政", gmap: "https://maps.app.goo.gl/EDMWrsaShahur8gy6"},
  { id: 3, name: "大漁", gmap: "https://maps.app.goo.gl/6CdPPXZcU6MDk8B27"},
  { id: 4, name: "レストラン マダム・トキ", gmap: "https://maps.app.goo.gl/C1xSbKgYDfLVwVBi6"},
  { id: 5, name: "アムール（Amour）", gmap: "https://maps.app.goo.gl/E4ufP7AqM5EQT1AM6"},
  { id: 6, name: "山の茶屋", gmap: "https://maps.app.goo.gl/zpz7jA9NwreUHcL96"},
  { id: 7, name: "分とく山", gmap: "https://maps.app.goo.gl/H6j4w8mLQREjLVw79"},
  { id: 8, name: "おすもじ処 うを徳", gmap: "https://maps.app.goo.gl/8tJQtBL6gAgCsi8ZA"},
  { id: 9, name: "焼肉 思食", gmap: "https://maps.app.goo.gl/7qmkGiYuhwVaJS8j6"},
  { id: 10, name: "手打ち蕎麦 丹想庵 健次郎", gmap: "https://maps.app.goo.gl/XZHnHvNJ5n6vshFw9"},
  { id: 11, name: "天ぷら 福たろう", gmap: "https://maps.app.goo.gl/1NqYa4sqLqFknwD97"},
  { id: 12, name: "三友居", gmap: "https://maps.app.goo.gl/ntMQbNUPXaZyidga8"},
  { id: 13, name: "蘭麻", gmap: "https://maps.app.goo.gl/K85hq2XiFsXjsAqD6"},
  { id: 14, name: "定谷", gmap: "https://maps.app.goo.gl/s8YfwE2vhCU5vAzm6"},
  { id: 15, name: "帰燕", gmap: "https://maps.app.goo.gl/iDiWxDtgyfYKcwXRA"},
  { id: 16, name: "浅草 ひら山", gmap: "https://maps.app.goo.gl/qdCwmykPEExTxvvr6"},
  { id: 17, name: "炭火焼鳥・鰻 居酒屋 鳥長 清澄白河", gmap: "https://maps.app.goo.gl/nDwTGH6RQj3YnLqZ6"},
  { id: 18, name: "和食 板垣", gmap: "https://maps.app.goo.gl/3LM9TcXXFTZJ7yjt6"},
  { id: 19, name: "いまここ", gmap: "https://maps.app.goo.gl/yTqis3CPY6ayBDRK9"},
  { id: 20, name: "谷や 和", gmap: "https://maps.app.goo.gl/T7tVjnaV9JGZGKTLA"},
  { id: 21, name: "村松", gmap: "https://maps.app.goo.gl/2b5KGrScDDJzKCs86"},
  { id: 22, name: "天ぷら はせ川", gmap: "https://maps.app.goo.gl/zztxouFtFATuAncE8"},
  { id: 23, name: "くじら料理 うずら", gmap: "https://maps.app.goo.gl/J5chPHV9tqxbRPnw7"},
  { id: 24, name: "今福", gmap: "https://maps.app.goo.gl/ixSnnh8BspyX9JSr8"},
  { id: 25, name: "雙柿庵", gmap: "https://maps.app.goo.gl/2KhUu3gFJ2k5kas9A"},
  { id: 26, name: "SHIGEtei", gmap: "https://maps.app.goo.gl/yARmVtT3vxPUiC839"},
  { id: 27, name: "3110NZ by LDH kitchen", gmap: "https://maps.app.goo.gl/rECv2phHeSseNhKp7"},
  { id: 28, name: "高嶋家", gmap: "https://maps.app.goo.gl/USRnVZMwwn8hdrG99"},
  { id: 29, name: "車屋", gmap: "https://maps.app.goo.gl/VJXA32jy4LxaqSRSA"},
  { id: 30, name: "根津のパン", gmap: "https://maps.app.goo.gl/AaQi7tjRZm3kWvT27"},
]